# Generated by Django 5.0 on 2023-12-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
