# Generated by Django 5.0 on 2023-12-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome Completo')),
                ('doc', models.IntegerField(unique=True, verbose_name='CPF/CNPJ')),
                ('is_cpf', models.BooleanField(default=True)),
                ('telefone', models.IntegerField(blank=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=254, verbose_name='Senha')),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Viajante',
        ),
    ]
