# Generated by Django 5.0 on 2023-12-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0004_agencia_rename_customuser_viajante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencia',
            name='is_cpf',
        ),
        migrations.RemoveField(
            model_name='viajante',
            name='is_cpf',
        ),
        migrations.AddField(
            model_name='viajante',
            name='cod',
            field=models.CharField(blank=True, max_length=254, verbose_name='Código do Roteiro'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='doc',
            field=models.IntegerField(unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nome',
            field=models.CharField(max_length=254, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='viajante',
            name='doc',
            field=models.IntegerField(unique=True, verbose_name='CPF'),
        ),
    ]
