# Generated by Django 4.2.9 on 2024-01-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0005_remove_agencia_is_cpf_remove_viajante_is_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='doc',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='viajante',
            name='doc',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='viajante',
            name='telefone',
            field=models.CharField(blank=True, max_length=254, verbose_name='Telefone'),
        ),
    ]
