# Generated by Django 4.2.9 on 2024-01-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0006_alter_agencia_doc_alter_agencia_telefone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viajante',
            new_name='Usuario',
        ),
    ]
