# Generated by Django 4.2.9 on 2024-01-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0007_rename_viajante_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cod',
        ),
    ]
