# Generated by Django 5.0.1 on 2024-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0008_remove_usuario_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome Restaurante')),
                ('descricao', models.CharField(max_length=254, verbose_name='Descrição')),
                ('cidade', models.CharField(max_length=254, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=254, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=254, verbose_name='Rua')),
                ('telefone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto_turistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome do Ponto')),
                ('descricao', models.CharField(max_length=254, verbose_name='Descrição')),
                ('cidade', models.CharField(max_length=254, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=254, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=254, verbose_name='Rua')),
            ],
        ),
    ]
