# Generated by Django 5.0.1 on 2024-01-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0009_cadastro_restaurante_ponto_turistico'),
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=254, unique=True, verbose_name='cidade')),
                ('descricao', models.CharField(max_length=254, verbose_name='descricao')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
