# Generated by Django 5.0.1 on 2024-01-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0010_cidade_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agencia',
        ),
    ]
