# Generated by Django 5.0.1 on 2024-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0011_delete_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome Fantasia')),
                ('doc', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=254, verbose_name='Senha')),
            ],
        ),
        migrations.AlterField(
            model_name='cidade',
            name='descricao',
            field=models.CharField(max_length=254, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome_cidade',
            field=models.SlugField(max_length=254, unique=True, verbose_name='cidade'),
        ),
    ]
