# Generated by Django 5.0.1 on 2024-01-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0012_agencia_alter_cidade_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='descricao',
            field=models.TextField(verbose_name='descrição'),
        ),
    ]
