# Generated by Django 5.0.1 on 2024-01-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0013_alter_cidade_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=254, verbose_name='Nome do Ponto')),
                ('descricao', models.CharField(max_length=254, verbose_name='Descrição')),
                ('cidade', models.CharField(max_length=254, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=254, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=254, verbose_name='Rua')),
                ('telefone', models.CharField(blank=True, max_length=14, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro_Restaurante',
        ),
        migrations.DeleteModel(
            name='Ponto_turistico',
        ),
    ]
