# Generated by Django 5.0.1 on 2024-01-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0014_local_delete_cadastro_restaurante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartravel.cidade'),
        ),
    ]
