# Generated by Django 4.2.8 on 2024-01-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0015_alter_local_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='smartravel.cidade'),
        ),
    ]
