# Generated by Django 4.2.8 on 2024-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0016_alter_local_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=254, verbose_name='Nome Completo')),
                ('doc', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=254, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=254, verbose_name='Senha')),
            ],
        ),
    ]
