# Generated by Django 5.0.1 on 2024-01-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0017_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='tipo',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('museu', 'Museu'), ('hotel', 'Hotel')], default='restaurante', max_length=20),
        ),
    ]
