# Generated by Django 5.0.1 on 2024-02-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0018_local_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='tipo',
        ),
    ]
