# Generated by Django 5.0.1 on 2024-02-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0019_remove_local_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='tipo',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('museu', 'Museu'), ('hotel', 'Hotel')], default='restaurante', max_length=20),
        ),
    ]
