# Generated by Django 5.0.1 on 2024-02-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0020_local_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='nome_local',
            field=models.CharField(max_length=254, verbose_name='Nome do Local'),
        ),
    ]
