# Generated by Django 5.0.1 on 2024-02-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0021_alter_local_nome_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('categorias', models.CharField(max_length=100)),
            ],
        ),
    ]
