# Generated by Django 5.0.1 on 2024-02-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0022_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.CharField(choices=[('restaurantes', 'Restaurante'), ('museus', 'Museu'), ('hoteis', 'Hotel')], default='restaurante', max_length=20),
        ),
    ]
