# Generated by Django 5.0.1 on 2024-02-02 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0023_alter_local_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locais', to='smartravel.tipo'),
        ),
    ]
