# Generated by Django 5.0.1 on 2024-02-02 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0024_tipo_alter_local_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='smartravel.categorias'),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
