# Generated by Django 5.0.1 on 2024-02-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0025_alter_local_tipo_delete_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
