# Generated by Django 5.0.1 on 2024-02-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0026_alter_local_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
