# Generated by Django 5.0.1 on 2024-02-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartravel', '0027_localcarrinho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalCarrinho',
        ),
    ]
